---
# Vagrant hostname and IP configuration.
vagrant_hostname: local.dev
vagrant_ip: 192.168.33.88

# A list of synced folders, with the keys 'local_path', 'destination', and 'id'.
vagrant_synced_folders:
  - local_path: ~/Sites/drupal
    destination: /var/www/
    excluded_paths: [".git/"]
    id: drupal
    type: nfs

# Memory and CPU to use for this VM.
vagrant_memory: 768
vagrant_cpus: 2

# Other variables in this file will be used during Ansible provisioning.
php_enable_php_fpm: true
php_packages:
  - php5
  - php5-fpm
  - php5-cli
  - php5-common
  - php5-dev
  - php5-gd
  - php5-mysql
  - php-pear
php_webserver_daemon: "nginx"
# get newer nginx (1.6+)
nginx_default_release: "wheezy-backports"
mariadb_root_password: root
mariadb_bind_address: "0.0.0.0"
drush_version: master

# Comment out any extra utilities you don't want to install.
installed_extras:
  - mailhog
  - memcached
  - xdebug
  - xhprof

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
  - "8025"
  - "8080"
  - "8443"

php_memory_limit: "256M"
php_display_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"

# Disable main XDebug components unless needed.
php_xdebug_coverage_enable: 0
php_xdebug_default_enable: 0
